# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Release devcontainer features

on:
  workflow_dispatch:

env:
  PR_PERMISSIONS: ${{ github.event_name != 'pull_request' && 'write' || 'read' }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: ${{ env.PR_PERMISSIONS }}
      pull-requests: ${{ env.PR_PERMISSIONS }}
      packages: ${{ env.PR_PERMISSIONS }}
    steps:
    - uses: actions/checkout@v4

    - name: "Publish Features"
      uses: devcontainers/action@v1
      with:
        publish-features: "true"
        base-path-to-features: ".devcontainer/features/desktop-selkies"
        generate-docs: "false"
